set -g default-terminal "tmux-256color"

unbind %
bind | split-window -h 

unbind '"'
bind - split-window -v

unbind r
bind r source-file ~/.tmux.conf

unbind -T copy-mode-vi MouseDragEnd1Pane # don't exit copy mode when dragging with mouse

bind -r j resize-pane -D 5
bind -r k resize-pane -U 5
bind -r l resize-pane -R 5
bind -r h resize-pane -L 5

bind -r m resize-pane -Z

set -g mouse on
